config/routes.rb
Rails.application.routes.draw do
  get 'main/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :servers do
    resources :players
  end
  
  resources :items
  resources :creatures
  resources :quests

  root 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creature.rb
class Creature < ApplicationRecord
end

app/models/drop.rb
class Drop < ApplicationRecord
  belongs_to :monster
  belongs_to :item
end

app/models/food.rb
class Food < ApplicationRecord
end

app/models/hold.rb
class Hold < ApplicationRecord
  belongs_to :player
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/monster.rb
class Monster < ApplicationRecord
  has_many :drops
  has_many :items through: :drops
end

app/models/npc.rb
class Npc < ApplicationRecord
  has_many :quests
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :server
  has_many :holds
  has_many :items, through: :holds
  has_many :receives
  has_many :quests, through: :receives
end

app/models/quest.rb
class Quest < ApplicationRecord
  belongs_to :npc
  has_many :rewards
end

app/models/receive.rb
class Receive < ApplicationRecord
  belongs_to :quest
  belongs_to :player
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :quest
  belongs_to :item
end

app/models/server.rb
class Server < ApplicationRecord
  has_many :players, dependent: :destroy
end

app/models/weapon.rb
class Weapon < ApplicationRecord
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController

  def index
    @servers = Server.all
  end

  def show
    @server = Server.find(params[:id])
  end

  def new
  end

  def create
	@server = Server.new(server_params)
 
    @server.save
    redirect_to @server
  end

  def destroy
    @server = Server.find(params[:id])
    @server.destroy
 
    redirect_to servers_path
  end

  private
    def server_params
	  params.require(:server).permit(:running)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New Server</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">  
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>
  <script>$(document).ready(function() { $('body').bootstrapMaterialDesign(); });</script>
</head>
<body>

<div class="mx-auto" style="margin-top: 220;">
<div class="container">

	<h1>Server List</h1>
  <div class="list-group">

		<% @servers.each do |server| %>
			<div class="card" style="max-width:760px;">
				<div class="card-body">

					<div class="container">
						<div class="row">
							<div class="col-sm">
							Server id:
									<h5 class="card-title"><%= server.id %></h5>
							</div>

							<div class="col-sm">
								<div class="btn-group" role="group" aria-label="Basic example">
									<%= link_to 'Show', server_path(server), class: 'btn btn-primary' -%>
									<%= link_to 'Delete', server_path(server), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' -%>
									<!-- <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">Delete</button> -->
								</div>
							</div>

							<!-- Modal -->
							<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteConfirmation" aria-hidden="true">
								<div class="modal-dialog modal-dialog-centered" role="document">
									<div class="modal-content">
										<div class="modal-header">
											<h5 class="modal-title" id="exampleModalLongTitle">Delete server</h5>
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span>
											</button>
										</div>
										<div class="modal-body">
											You will delete this server. Are you sure?
										</div>
										<div class="modal-footer">
											<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
											<%= link_to 'Delete', server_path(server), method: :delete, class: 'btn btn-danger' -%>
										</div>
									</div>
								</div>
							</div>

						</div>
					</div>

				</div>
			</div>
		<% end %>

	</div>
</div>
</div>


</body>
</html>

app/views/servers/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New Server</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">  
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>
  <script>$(document).ready(function() { $('body').bootstrapMaterialDesign(); });</script>
</head>
<body>

<div class="mx-auto" style="margin-top: 220;">
<div class="container">

  <%= form_for :server, url: servers_path do |f| %>
    <!-- <%= f.check_box :running, class: 'form-check-input' -%> -->
    <div class="form-group">
      <div class="col-md-8">
        <%= f.check_box :running, class: "form-control" %>
        <%= f.submit "Create", class: 'btn btn-primary' -%>
      </div>
    </div>
  <% end %>

</div>
</div>

</body>
</html>

app/views/servers/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New Server</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">  
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>
  <script>$(document).ready(function() { $('body').bootstrapMaterialDesign(); });</script>
</head>
<body>

<div class="container">
	<div class="row clearfix">
    <div class="col-md-12 column">

      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">Server List</a></li>
          <li class="breadcrumb-item active" aria-current="page">Player List</li>
        </ol>
      </nav>
      
      <div class="row">

        <div class="col">
          <div class="page-header">
            <h1>
              Player List
            </h1>
            <h3>
              Server id:<%= @server.id %>
            </h3>
          </div>
        </div>

        <div class="col">
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newPlayer">New player</button>

          <div class="modal fade" id="newPlayer" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">

                <%= form_for([@server, @server.players.build]) do |f| %>

                  <div class="modal-header">
                    <h5 class="modal-title" id="newPlayerLabel">New player</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>

                  <div class="modal-body">

                    <%= f.label :name, class: "col-form-label" %><br>
                    <%= f.text_field :name, class: "form-control" %>

                    <%= f.label :career, class: "col-form-label" %><br>
                    <%= f.text_field :career, class: "form-control" %>

                    <%= f.label :level, class: "col-form-label" %><br>
                    <%= f.text_field :level, class: "form-control" %>

                    <%= f.label :health, class: "col-form-label" %><br>
                    <%= f.text_field :health, class: "form-control" %>

                  </div>
                  
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <!-- <button type="button" class="btn btn-primary">Create player</button> -->
                    <%= f.submit "Create player", class: 'btn btn-primary' -%>
                  </div>

                <% end %>
                
              </div>
            </div>
          </div>

        </div>

      </div>

      
        
      <div class="row clearfix">
        <div class="col-md-12 column">
          
          <% @server.players.each do |player| %>
            <div class="card" style="max-width:760px;">
              <div class="card-body">
                
                <h3 class="card-title"><%= player.name %></h3>

                <div class="container">
                  <div class="row">

                    <div class="col-sm">
                        
                    </div>

                    <div class="col-sm">
                      <div class="btn-group" role="group" aria-label="Basic example">
                        <%= link_to 'Show', [@server, player], class: 'btn btn-primary' -%>
                        <%= link_to 'Edit', [@server, player], class: 'btn btn-primary' -%>
                        <%= link_to 'Delete', [@server, player], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' -%></td>
                      </div>
                    </div>

                  </div>
                </div>
      
              </div>
            </div>

          <% end %>

            
        </div>
      </div>
    </div>
  </div>
</div>

</body>
</html>